services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-interview-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: ai-interview-frontend

    ports:
      - "8501:8501"

    environment:
      API_URL: "http://backend:8000"

    depends_on:
      - backend

    restart: unless-stopped